### ISSUE TITLE
Integrate this project with the new service catalog offer

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rstudio#16]
@brucehoff  introduced me to the new service catalog offer that allows a user (researchers, engineer) to seamlessly create an AWS remote instance. The user gets a session on the remote instance that allows to deploy a service of interest (e.g. RStudio, API service). The user can then access the service via the browser in the case where the service comes with a web client.

Here is a workflow that has the potential to become a standard at Sage:

- Create an AWS remote instance using Sage Service Catalog (see [instructions](https://sagebionetworks.jira.com/wiki/spaces/IT/pages/938836322/Service+Catalog+Provisioning#SSM-access-to-an-Instance))
- Use `ssm` to create a session on the remote instance.
- Clone a GitHub repository derived from the present repository (Sage-Bionetworks/docker-rstudio)
- `docker compose up` or `docker compose up --build` to start RStudio
- Update projects (mainly notebooks)
- Commit and push the changes to GitHub

Here is the process to update the Docker image built by the CI/CD workflow:
- Update Dockerfile or files used to build the image (e.g. conda environment config, renv.lock)
- Commit and push the changes to GH
- Create a GH release to trigger the CI/CD workflow that will then build and push the image to a Docker registry (e.g. DockerHub or Synapse)

### Task

- [ ] Follow the instructions shared by @brucehoff to instantiate an instance using the Service Catalog
- [ ] Deploy this project and try accessing RStudio
- [ ] Add a section to the instructions that describe how to use the setup described in this ticket.

**Comment by tschaffter** [comment]
### Update

@brucehoff was able to deploy this project to an EC2 created through the service catalog. The only issue reported is that our documentation mentions `docker compose` - instead of the more traditional `docker-compose` - but the new compose command is net yet well integrated on the unix-based instance deployed by Bruce.

```
[ssm-user@ip-10-41-24-173 docker-rstudio]$ sudo docker --version
Docker version 20.10.4, build d3cb89e
[ssm-user@ip-10-41-24-173 docker-rstudio]$ sudo docker compose up
docker: 'compose' is not a docker command.
See 'docker --help'
```

### TODO

- [x] Add a note to the README to install and use `docker-compose` if `docker compose` is not available on the host (done in #17)

**Comment by tschaffter** [comment]
Early feedback from Sagers is that it is easier for them to spin up a vanilla RStudio instance than using the Dockerized RStudio provided by this repository. The goal of this repo is to make experiments portable and reproducible, but that comes at the comes of know a bit about Docker. Also an advantage of this repo is that you don't need an AWS account.
